# Copy to config/config.yaml and edit
seed: 42
data:
  provider: mt5
  timezone: "UTC"
  symbols: ["EURUSD", "XAUUSD", "Volatility 75 Index"]
  timeframe: "M15"
strategy:
  name: "ai_ensemble"
  params: 
    rsi_period: 14
    rsi_buy: 30
    rsi_sell: 70
    ema_fast: 21
    ema_slow: 55
risk:
  balance_start: 10000
  risk_per_trade_pct: 0.5
  max_daily_loss_pct: 2.0
  max_consecutive_losses: 3
  cooldown_minutes_after_stopout: 60
execution:
  slippage_pips: 1.0
  tp_rr: 1.5
  hard_stop_pips: 20
logging:
  folder: "out"
  csv_trades: "out/trades.csv"
  csv_equity: "out/equity.csv"
