name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black ruff pytest

    - name: Windows-only - Install MetaTrader5
      if: runner.os == 'Windows'
      run: |
        pip install MetaTrader5==5.0.45

    - name: Lint with ruff
      run: |
        ruff check .

    - name: Check code formatting with black
      run: |
        black --check .

    - name: Test with pytest
      run: |
        pytest -q
