name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: "3.11"
            install_mt5: "false"
          - os: windows-latest
            python: "3.10"
            install_mt5: "true"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Show Python env
        run: |
          python -V
          pip -V

      - name: Install base deps (portable)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black ruff pytest

      - name: Install MetaTrader5 (Windows only)
        if: ${{ matrix.install_mt5 == 'true' }}
        run: |
          pip install MetaTrader5==5.0.45

      - name: Lint
        run: |
          ruff check .
          black --check .

      - name: Tests
        run: pytest -q
